### ISSUE TITLE
Saving discussions in a directory according to categories

### ISSUE THREAD

**Issue by shenweiyan** [King-of-Infinite-Space/gh-discussions-export#3]
This is a great tool. Can we consider saving discussions in a directory according to categories? Thank you.

**Comment by King-of-Infinite-Space** [comment]
Good idea. Feel free to implement it if you're interested.

**Comment by King-of-Infinite-Space** [comment]
Thanks for PR. I implemented it as an option (7762c68), with default config `subDirCategories: false`.

**Comment by shenweiyan** [comment]
Cool, That's Awesome!
